//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Salary_Restfull {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Salary_Restfull.IRestService")]
    public interface IRestService {
        
        // CODEGEN: Generating message contract since element name UsereEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetNetIncome", ReplyAction="http://tempuri.org/IRestService/GetNetIncomeResponse")]
        HRManagement.Salary_Restfull.GetNetIncomeResponse GetNetIncome(HRManagement.Salary_Restfull.GetNetIncomeRequest request);
        
        // CODEGEN: Generating message contract since element name UsereEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetGrossIncome", ReplyAction="http://tempuri.org/IRestService/GetGrossIncomeResponse")]
        HRManagement.Salary_Restfull.GetGrossIncomeResponse GetGrossIncome(HRManagement.Salary_Restfull.GetGrossIncomeRequest request);
        
        // CODEGEN: Generating message contract since element name GetContributionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetContributions", ReplyAction="http://tempuri.org/IRestService/GetContributionsResponse")]
        HRManagement.Salary_Restfull.GetContributionsResponse GetContributions(HRManagement.Salary_Restfull.GetContributionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNetIncomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNetIncome", Namespace="http://tempuri.org/", Order=0)]
        public HRManagement.Salary_Restfull.GetNetIncomeRequestBody Body;
        
        public GetNetIncomeRequest() {
        }
        
        public GetNetIncomeRequest(HRManagement.Salary_Restfull.GetNetIncomeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNetIncomeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsereEmail;
        
        public GetNetIncomeRequestBody() {
        }
        
        public GetNetIncomeRequestBody(string UsereEmail) {
            this.UsereEmail = UsereEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNetIncomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNetIncomeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRManagement.Salary_Restfull.GetNetIncomeResponseBody Body;
        
        public GetNetIncomeResponse() {
        }
        
        public GetNetIncomeResponse(HRManagement.Salary_Restfull.GetNetIncomeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNetIncomeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNetIncomeResult;
        
        public GetNetIncomeResponseBody() {
        }
        
        public GetNetIncomeResponseBody(int GetNetIncomeResult) {
            this.GetNetIncomeResult = GetNetIncomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGrossIncomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGrossIncome", Namespace="http://tempuri.org/", Order=0)]
        public HRManagement.Salary_Restfull.GetGrossIncomeRequestBody Body;
        
        public GetGrossIncomeRequest() {
        }
        
        public GetGrossIncomeRequest(HRManagement.Salary_Restfull.GetGrossIncomeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGrossIncomeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsereEmail;
        
        public GetGrossIncomeRequestBody() {
        }
        
        public GetGrossIncomeRequestBody(string UsereEmail) {
            this.UsereEmail = UsereEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGrossIncomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGrossIncomeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRManagement.Salary_Restfull.GetGrossIncomeResponseBody Body;
        
        public GetGrossIncomeResponse() {
        }
        
        public GetGrossIncomeResponse(HRManagement.Salary_Restfull.GetGrossIncomeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGrossIncomeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetGrossIncomeResult;
        
        public GetGrossIncomeResponseBody() {
        }
        
        public GetGrossIncomeResponseBody(int GetGrossIncomeResult) {
            this.GetGrossIncomeResult = GetGrossIncomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContributionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContributions", Namespace="http://tempuri.org/", Order=0)]
        public HRManagement.Salary_Restfull.GetContributionsRequestBody Body;
        
        public GetContributionsRequest() {
        }
        
        public GetContributionsRequest(HRManagement.Salary_Restfull.GetContributionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContributionsRequestBody {
        
        public GetContributionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContributionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContributionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRManagement.Salary_Restfull.GetContributionsResponseBody Body;
        
        public GetContributionsResponse() {
        }
        
        public GetContributionsResponse(HRManagement.Salary_Restfull.GetContributionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContributionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HRManagement.Salary_Restfull.ArrayOfString GetContributionsResult;
        
        public GetContributionsResponseBody() {
        }
        
        public GetContributionsResponseBody(HRManagement.Salary_Restfull.ArrayOfString GetContributionsResult) {
            this.GetContributionsResult = GetContributionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : HRManagement.Salary_Restfull.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<HRManagement.Salary_Restfull.IRestService>, HRManagement.Salary_Restfull.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRManagement.Salary_Restfull.GetNetIncomeResponse HRManagement.Salary_Restfull.IRestService.GetNetIncome(HRManagement.Salary_Restfull.GetNetIncomeRequest request) {
            return base.Channel.GetNetIncome(request);
        }
        
        public int GetNetIncome(string UsereEmail) {
            HRManagement.Salary_Restfull.GetNetIncomeRequest inValue = new HRManagement.Salary_Restfull.GetNetIncomeRequest();
            inValue.Body = new HRManagement.Salary_Restfull.GetNetIncomeRequestBody();
            inValue.Body.UsereEmail = UsereEmail;
            HRManagement.Salary_Restfull.GetNetIncomeResponse retVal = ((HRManagement.Salary_Restfull.IRestService)(this)).GetNetIncome(inValue);
            return retVal.Body.GetNetIncomeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRManagement.Salary_Restfull.GetGrossIncomeResponse HRManagement.Salary_Restfull.IRestService.GetGrossIncome(HRManagement.Salary_Restfull.GetGrossIncomeRequest request) {
            return base.Channel.GetGrossIncome(request);
        }
        
        public int GetGrossIncome(string UsereEmail) {
            HRManagement.Salary_Restfull.GetGrossIncomeRequest inValue = new HRManagement.Salary_Restfull.GetGrossIncomeRequest();
            inValue.Body = new HRManagement.Salary_Restfull.GetGrossIncomeRequestBody();
            inValue.Body.UsereEmail = UsereEmail;
            HRManagement.Salary_Restfull.GetGrossIncomeResponse retVal = ((HRManagement.Salary_Restfull.IRestService)(this)).GetGrossIncome(inValue);
            return retVal.Body.GetGrossIncomeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRManagement.Salary_Restfull.GetContributionsResponse HRManagement.Salary_Restfull.IRestService.GetContributions(HRManagement.Salary_Restfull.GetContributionsRequest request) {
            return base.Channel.GetContributions(request);
        }
        
        public HRManagement.Salary_Restfull.ArrayOfString GetContributions() {
            HRManagement.Salary_Restfull.GetContributionsRequest inValue = new HRManagement.Salary_Restfull.GetContributionsRequest();
            inValue.Body = new HRManagement.Salary_Restfull.GetContributionsRequestBody();
            HRManagement.Salary_Restfull.GetContributionsResponse retVal = ((HRManagement.Salary_Restfull.IRestService)(this)).GetContributions(inValue);
            return retVal.Body.GetContributionsResult;
        }
    }
}
